//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using Cqrs.Authentication;
using Cqrs.Services;

namespace HelloWorld.Domain.Akka.Services
{
	[GeneratedCode("CQRS UML Code Generator", "1.601.932")]
	[ServiceContract(Namespace="https://getcqrs.net/Domain/Akka/1001/")]
	public partial interface IHelloWorldExampleService : IEventService<Cqrs.Authentication.SingleSignOnToken>
	{

		[OperationContract]
		IServiceResponse SayHelloWorld(IServiceRequestWithData<Cqrs.Authentication.SingleSignOnToken, HelloWorldExampleSayHelloWorldParameters> serviceRequest);

		[OperationContract]
		IServiceResponse ReplyToHelloWorld(IServiceRequestWithData<Cqrs.Authentication.SingleSignOnToken, HelloWorldExampleReplyToHelloWorldParameters> serviceRequest);

		[OperationContract]
		IServiceResponse EndConversation(IServiceRequestWithData<Cqrs.Authentication.SingleSignOnToken, HelloWorldExampleEndConversationParameters> serviceRequest);
	}

	/// <summary>
	/// The parameters for the <see cref="IHelloWorldExampleService.SayHelloWorld" /> method.
	/// </summary>
	[GeneratedCode("CQRS UML Code Generator", "1.601.932")]
	[ServiceContract(Namespace="https://getcqrs.net/Domain/Akka/1001/")]
	public partial class HelloWorldExampleSayHelloWorldParameters
	{
		[DataMember]
		public System.Guid Rsn { get; set; }

		[DataMember]
		public string FirstName { get; set; }

	}

	/// <summary>
	/// The parameters for the <see cref="IHelloWorldExampleService.ReplyToHelloWorld" /> method.
	/// </summary>
	[GeneratedCode("CQRS UML Code Generator", "1.601.932")]
	[ServiceContract(Namespace="https://getcqrs.net/Domain/Akka/1001/")]
	public partial class HelloWorldExampleReplyToHelloWorldParameters
	{
		[DataMember]
		public System.Guid Rsn { get; set; }

		[DataMember]
		public string FirstName { get; set; }

	}

	/// <summary>
	/// The parameters for the <see cref="IHelloWorldExampleService.EndConversation" /> method.
	/// </summary>
	[GeneratedCode("CQRS UML Code Generator", "1.601.932")]
	[ServiceContract(Namespace="https://getcqrs.net/Domain/Akka/1001/")]
	public partial class HelloWorldExampleEndConversationParameters
	{
		[DataMember]
		public System.Guid Rsn { get; set; }

		[DataMember]
		public string FirstName { get; set; }

	}
}
