//------------------------------------------------------------------------------
// <auto-generated>
// 	This code was generated by a tool
// 	Changes to this file will be lost if the code is regenerated.
// EventToHubProxyTemplate.t4
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Cqrs.Authentication;
using Cqrs.Domain;
using Cqrs.Events;

namespace HelloWorld.Domain.Host.Web.SignalR
{
	// [GeneratedCode("CQRS UML Code Generator", "1.601.932")]
	public  partial class EventToHubProxy
		: IEventHandler<Cqrs.Authentication.SingleSignOnToken, HelloWorld.Domain.Akka.Events.HelloWorldSaid>
	{
		#region Implementation of IEventHandler<in HelloWorld.Domain.Akka.Events.HelloWorldSaid>

		public void Handle(HelloWorld.Domain.Akka.Events.HelloWorldSaid @event)
		{
			bool continueExecute = true;
			OnHandle(@event, ref continueExecute);
			if (!continueExecute)
				return;
			HandleGenericEvent(@event);
			OnHandled(@event);
		}

		#endregion

		partial void OnHandle(HelloWorld.Domain.Akka.Events.HelloWorldSaid @event, ref bool continueExecute);

		partial void OnHandled(HelloWorld.Domain.Akka.Events.HelloWorldSaid @event);
	}
}
