//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion

using System.CodeDom.Compiler;
using System.Web.Mvc;

namespace HelloWorld.Domain.Controllers
{
	/// <summary>
	/// An <see cref="Controller">API controller</see> for all publically exposed sample methods and queries.
	/// </summary>
	[GeneratedCode("CQRS UML Code Generator", "1.601.932")]
	[RequireHttps]
	public partial class BuiltInController : Controller
	{	}
}
