//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using Cqrs.Configuration;
using Cqrs.Authentication;
using Cqrs.Repositories.Queries;
using HelloWorld.Domain.Factories;

namespace HelloWorld.Domain.Akka.Repositories.Queries.Strategies
{
	[GeneratedCode("CQRS UML Code Generator", "1.601.932")]
	public partial class DailyNewConversationsReportQueryStrategyBuilder : QueryBuilder<DailyNewConversationsReportQueryStrategy, Entities.DailyNewConversationsReportEntity>, IDailyNewConversationsReportQueryStrategyBuilder
	{
		public DailyNewConversationsReportQueryStrategyBuilder(IDomainDataStoreFactory dataStoreFactory, IDependencyResolver dependencyResolver)
			: base(dataStoreFactory.GetDailyNewConversationsReportDataStore(), dependencyResolver)
		{
		}

		#region Overrides of QueryBuilder<DailyNewConversationsReportQueryStrategy,Entities.DailyNewConversationsReportEntity>

		protected override IQueryable<Entities.DailyNewConversationsReportEntity> GeneratePredicate(QueryPredicate queryPredicate, IQueryable<Entities.DailyNewConversationsReportEntity> leftHandQueryable = null)
		{
			DailyNewConversationsReportQueryStrategy queryStrategy = GetNullQueryStrategy();
			SortedSet<QueryParameter> parameters = queryPredicate.Parameters;

			IQueryable<Entities.DailyNewConversationsReportEntity> resultingQueryable = null;

			resultingQueryable
				= GeneratePredicateWithPermissionScopeAny<Cqrs.Authentication.SingleSignOnToken>(queryPredicate, leftHandQueryable)
				?? GeneratePredicateWithPermissionScopeUser<Cqrs.Authentication.SingleSignOnToken>(queryPredicate, leftHandQueryable)
				?? GeneratePredicateWithPermissionScopeCompany<Cqrs.Authentication.SingleSignOnToken>(queryPredicate, leftHandQueryable)
				?? GeneratePredicateWithPermissionScopeCompanyAndUser<Cqrs.Authentication.SingleSignOnToken>(queryPredicate, leftHandQueryable);

			if (resultingQueryable != null)
				return resultingQueryable;

			throw new InvalidOperationException("No known predicate could be generated.");
		}

		#endregion

		protected override void ApplySorting(DailyNewConversationsReportQueryStrategy queryStrategy, ref IQueryable<Entities.DailyNewConversationsReportEntity> queryable)
		{
			var orderQueryable = (IOrderedQueryable<Entities.DailyNewConversationsReportEntity>)queryable;

			int index = 0;
			foreach (Func<int, DailyNewConversationsReportQueryStrategy> sortingMethod in queryStrategy.SortingList)
			{

			}
			queryable = orderQueryable;
		}

	}
}
