//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion
using Cqrs.Domain;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using Cqrs.Authentication;
using Cqrs.Repositories.Queries;

namespace HelloWorld.Domain.Akka.Repositories.Queries.Strategies
{
	[GeneratedCode("CQRS UML Code Generator", "1.601.932")]
	public partial class DailyNewConversationsReportQueryStrategy : QueryStrategy, IDailyNewConversationsReportQueryStrategy
	{
		protected IAuthenticationTokenHelper<Cqrs.Authentication.SingleSignOnToken> AuthenticationTokenHelper { get; private set; }

		internal IList<Func<int, DailyNewConversationsReportQueryStrategy>> SortingList { get; set; }

		public DailyNewConversationsReportQueryStrategy(IAuthenticationTokenHelper<Cqrs.Authentication.SingleSignOnToken> authenticationTokenHelper)
		{
			AuthenticationTokenHelper = authenticationTokenHelper;
			SortingList = new List<Func<int, DailyNewConversationsReportQueryStrategy>>();
		}

	}
}
