//------------------------------------------------------------------------------
// <auto-generated>
// 	This code was generated by a tool
// 	Changes to this file will be lost if the code is regenerated.
// QueryBuilderInterfaceTemplate.t4
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion


using System.CodeDom.Compiler;
using System.Collections.Generic;
using Cqrs.Repositories.Queries;

namespace HelloWorld.Domain.Akka.Repositories.Queries.Strategies
{
	[GeneratedCode("CQRS UML Code Generator", "1.601.932")]
	public partial interface IDailyNewConversationsReportQueryStrategyBuilder : IQueryBuilder<DailyNewConversationsReportQueryStrategy, Entities.DailyNewConversationsReport>
	{
	}
}
