//------------------------------------------------------------------------------
// <auto-generated>
// 	This code was generated by a tool
// 	Changes to this file will be lost if the code is regenerated.
// EntityTemplate.t4
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion

using Cqrs.Domain;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using Cqrs.Entities;
 
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Runtime.Serialization;

namespace HelloWorld.Domain.Akka.Entities
{
	[GeneratedCode("CQRS UML Code Generator", "1.601.932")]
	[Serializable]
	[DataContract]
	[Table(Name = "DailyNewConversationsReportEntity")]
	[ServiceContract(Namespace="https://getcqrs.net/Domain/Akka/Entities/1001/")]
	public  partial class DailyNewConversationsReport : Entity, IDailyNewConversationsReport
	{
		[DataMember]
		[Column(IsPrimaryKey = true)]
		public override Guid Rsn { get; set; }

		[DataMember]
		[Column]
		public override int SortingOrder { get; set; }

		[DataMember]
		[Column]
		public override bool IsLogicallyDeleted { get; set; }

		[DataMember]
		[Column]
		public virtual int Number { get; set; }


		[DataMember]
		[Column]
		public virtual DateTime Date { get; set; }

	}
}
