//------------------------------------------------------------------------------
// <auto-generated>
// 	This code was generated by a tool
// 	Changes to this file will be lost if the code is regenerated.
// EntityRepositoryTemplate.t4
// </auto-generated>
//------------------------------------------------------------------------------

#region Copyright
// -----------------------------------------------------------------------
// <copyright company="cdmdotnet Limited">
//     Copyright cdmdotnet Limited. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------
#endregion

using Cqrs.Domain;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using Cqrs.Repositories;
using HelloWorld.Domain.Factories;
using HelloWorld.Domain.Akka.Repositories.Queries.Strategies;

namespace HelloWorld.Domain.Akka.Entities.Repositories
{
	[GeneratedCode("CQRS UML Code Generator", "1.601.932")]
	public partial class DailyNewConversationsReportRepository : Repository<DailyNewConversationsReportQueryStrategy, DailyNewConversationsReportQueryStrategyBuilder, Entities.DailyNewConversationsReport>, IDailyNewConversationsReportRepository
	{
		public DailyNewConversationsReportRepository(IDomainDataStoreFactory dataStoreFactory, DailyNewConversationsReportQueryStrategyBuilder dailyNewConversationsReportQueryBuilder)
			: base(dataStoreFactory.GetDailyNewConversationsReportDataStore, dailyNewConversationsReportQueryBuilder)
		{
		}
	}
}
